package com.wenyanwen123.buy.commons.domain.learningdb;

import java.math.BigDecimal;
import java.util.Date;

public class FlashSaleGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flash_sale_goods.id
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flash_sale_goods.goods_id
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flash_sale_goods.seckill_price
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private BigDecimal seckillPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flash_sale_goods.stock_count
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private Integer stockCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flash_sale_goods.start_time
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flash_sale_goods.start_timestamp
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private Integer startTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flash_sale_goods.end_time
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flash_sale_goods.end_timestamp
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private Integer endTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flash_sale_goods.id
     *
     * @return the value of t_flash_sale_goods.id
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flash_sale_goods.id
     *
     * @param id the value for t_flash_sale_goods.id
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flash_sale_goods.goods_id
     *
     * @return the value of t_flash_sale_goods.goods_id
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flash_sale_goods.goods_id
     *
     * @param goodsId the value for t_flash_sale_goods.goods_id
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flash_sale_goods.seckill_price
     *
     * @return the value of t_flash_sale_goods.seckill_price
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public BigDecimal getSeckillPrice() {
        return seckillPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flash_sale_goods.seckill_price
     *
     * @param seckillPrice the value for t_flash_sale_goods.seckill_price
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setSeckillPrice(BigDecimal seckillPrice) {
        this.seckillPrice = seckillPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flash_sale_goods.stock_count
     *
     * @return the value of t_flash_sale_goods.stock_count
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public Integer getStockCount() {
        return stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flash_sale_goods.stock_count
     *
     * @param stockCount the value for t_flash_sale_goods.stock_count
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setStockCount(Integer stockCount) {
        this.stockCount = stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flash_sale_goods.start_time
     *
     * @return the value of t_flash_sale_goods.start_time
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flash_sale_goods.start_time
     *
     * @param startTime the value for t_flash_sale_goods.start_time
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flash_sale_goods.start_timestamp
     *
     * @return the value of t_flash_sale_goods.start_timestamp
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public Integer getStartTimestamp() {
        return startTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flash_sale_goods.start_timestamp
     *
     * @param startTimestamp the value for t_flash_sale_goods.start_timestamp
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setStartTimestamp(Integer startTimestamp) {
        this.startTimestamp = startTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flash_sale_goods.end_time
     *
     * @return the value of t_flash_sale_goods.end_time
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flash_sale_goods.end_time
     *
     * @param endTime the value for t_flash_sale_goods.end_time
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flash_sale_goods.end_timestamp
     *
     * @return the value of t_flash_sale_goods.end_timestamp
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public Integer getEndTimestamp() {
        return endTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flash_sale_goods.end_timestamp
     *
     * @param endTimestamp the value for t_flash_sale_goods.end_timestamp
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setEndTimestamp(Integer endTimestamp) {
        this.endTimestamp = endTimestamp;
    }
}