package com.wenyanwen123.buy.commons.domain.learningdb;

import java.math.BigDecimal;
import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_id
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_name
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_title
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private String goodsTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_img
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private String goodsImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_detail
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private String goodsDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_price
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_stock
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private Integer goodsStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.total_sales
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private Integer totalSales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.create_time
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.create_timestamp
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private Integer createTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.is_on_sale
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private Boolean isOnSale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.is_delete
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_id
     *
     * @return the value of t_goods.goods_id
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_id
     *
     * @param goodsId the value for t_goods.goods_id
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_name
     *
     * @return the value of t_goods.goods_name
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_name
     *
     * @param goodsName the value for t_goods.goods_name
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_title
     *
     * @return the value of t_goods.goods_title
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public String getGoodsTitle() {
        return goodsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_title
     *
     * @param goodsTitle the value for t_goods.goods_title
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setGoodsTitle(String goodsTitle) {
        this.goodsTitle = goodsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_img
     *
     * @return the value of t_goods.goods_img
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_img
     *
     * @param goodsImg the value for t_goods.goods_img
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_detail
     *
     * @return the value of t_goods.goods_detail
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public String getGoodsDetail() {
        return goodsDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_detail
     *
     * @param goodsDetail the value for t_goods.goods_detail
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setGoodsDetail(String goodsDetail) {
        this.goodsDetail = goodsDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_price
     *
     * @return the value of t_goods.goods_price
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_price
     *
     * @param goodsPrice the value for t_goods.goods_price
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_stock
     *
     * @return the value of t_goods.goods_stock
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public Integer getGoodsStock() {
        return goodsStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_stock
     *
     * @param goodsStock the value for t_goods.goods_stock
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setGoodsStock(Integer goodsStock) {
        this.goodsStock = goodsStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.total_sales
     *
     * @return the value of t_goods.total_sales
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public Integer getTotalSales() {
        return totalSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.total_sales
     *
     * @param totalSales the value for t_goods.total_sales
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setTotalSales(Integer totalSales) {
        this.totalSales = totalSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.create_time
     *
     * @return the value of t_goods.create_time
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.create_time
     *
     * @param createTime the value for t_goods.create_time
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.create_timestamp
     *
     * @return the value of t_goods.create_timestamp
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public Integer getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.create_timestamp
     *
     * @param createTimestamp the value for t_goods.create_timestamp
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setCreateTimestamp(Integer createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.is_on_sale
     *
     * @return the value of t_goods.is_on_sale
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public Boolean getIsOnSale() {
        return isOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.is_on_sale
     *
     * @param isOnSale the value for t_goods.is_on_sale
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setIsOnSale(Boolean isOnSale) {
        this.isOnSale = isOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.is_delete
     *
     * @return the value of t_goods.is_delete
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.is_delete
     *
     * @param isDelete the value for t_goods.is_delete
     *
     * @mbg.generated Thu Feb 20 21:17:49 CST 2020
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}