package com.wenyanwen123.buy.dao.learningdb;

import com.wenyanwen123.buy.commons.domain.learningdb.SeckillOrder;
import com.wenyanwen123.buy.commons.domain.learningdb.SeckillOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeckillOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_order
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    long countByExample(SeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_order
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    int deleteByExample(SeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_order
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    int deleteByPrimaryKey(Long seckillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_order
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    int insert(SeckillOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_order
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    int insertSelective(SeckillOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_order
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    List<SeckillOrder> selectByExample(SeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_order
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    SeckillOrder selectByPrimaryKey(Long seckillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_order
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") SeckillOrder record, @Param("example") SeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_order
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    int updateByExample(@Param("record") SeckillOrder record, @Param("example") SeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_order
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    int updateByPrimaryKeySelective(SeckillOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill_order
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    int updateByPrimaryKey(SeckillOrder record);
}