package com.wenyanwen123.buy.common.domain.learningdb;

import java.util.Date;

public class SeckillOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order.seckill_id
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    private Long seckillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order.order_num
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    private String orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order.user_id
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order.goods_id
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order.order_channel
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    private Integer orderChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order.order_status
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order.create_time
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order.create_timestamp
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    private Integer createTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order.pay_date
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    private Date payDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order.pay_timestamp
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    private Integer payTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order.is_del
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order.seckill_id
     *
     * @return the value of t_seckill_order.seckill_id
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public Long getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order.seckill_id
     *
     * @param seckillId the value for t_seckill_order.seckill_id
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public void setSeckillId(Long seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order.order_num
     *
     * @return the value of t_seckill_order.order_num
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order.order_num
     *
     * @param orderNum the value for t_seckill_order.order_num
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order.user_id
     *
     * @return the value of t_seckill_order.user_id
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order.user_id
     *
     * @param userId the value for t_seckill_order.user_id
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order.goods_id
     *
     * @return the value of t_seckill_order.goods_id
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order.goods_id
     *
     * @param goodsId the value for t_seckill_order.goods_id
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order.order_channel
     *
     * @return the value of t_seckill_order.order_channel
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public Integer getOrderChannel() {
        return orderChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order.order_channel
     *
     * @param orderChannel the value for t_seckill_order.order_channel
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public void setOrderChannel(Integer orderChannel) {
        this.orderChannel = orderChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order.order_status
     *
     * @return the value of t_seckill_order.order_status
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order.order_status
     *
     * @param orderStatus the value for t_seckill_order.order_status
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order.create_time
     *
     * @return the value of t_seckill_order.create_time
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order.create_time
     *
     * @param createTime the value for t_seckill_order.create_time
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order.create_timestamp
     *
     * @return the value of t_seckill_order.create_timestamp
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public Integer getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order.create_timestamp
     *
     * @param createTimestamp the value for t_seckill_order.create_timestamp
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public void setCreateTimestamp(Integer createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order.pay_date
     *
     * @return the value of t_seckill_order.pay_date
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order.pay_date
     *
     * @param payDate the value for t_seckill_order.pay_date
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order.pay_timestamp
     *
     * @return the value of t_seckill_order.pay_timestamp
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public Integer getPayTimestamp() {
        return payTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order.pay_timestamp
     *
     * @param payTimestamp the value for t_seckill_order.pay_timestamp
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public void setPayTimestamp(Integer payTimestamp) {
        this.payTimestamp = payTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order.is_del
     *
     * @return the value of t_seckill_order.is_del
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order.is_del
     *
     * @param isDel the value for t_seckill_order.is_del
     *
     * @mbg.generated Sat Feb 22 20:47:12 CST 2020
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}