package com.wenyanwen123.buy.common.domain.learningdb;

import java.math.BigDecimal;

public class SeckillOrderSnapshot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order_snapshot.snapshot_id
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    private Long snapshotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order_snapshot.order_num
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    private String orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order_snapshot.goods_count
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    private Integer goodsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order_snapshot.goods_price
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order_snapshot.seckill_price
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    private BigDecimal seckillPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order_snapshot.goods_name
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order_snapshot.goods_title
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    private String goodsTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order_snapshot.goods_img
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    private String goodsImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill_order_snapshot.goods_detail
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    private String goodsDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order_snapshot.snapshot_id
     *
     * @return the value of t_seckill_order_snapshot.snapshot_id
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public Long getSnapshotId() {
        return snapshotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order_snapshot.snapshot_id
     *
     * @param snapshotId the value for t_seckill_order_snapshot.snapshot_id
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public void setSnapshotId(Long snapshotId) {
        this.snapshotId = snapshotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order_snapshot.order_num
     *
     * @return the value of t_seckill_order_snapshot.order_num
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order_snapshot.order_num
     *
     * @param orderNum the value for t_seckill_order_snapshot.order_num
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order_snapshot.goods_count
     *
     * @return the value of t_seckill_order_snapshot.goods_count
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order_snapshot.goods_count
     *
     * @param goodsCount the value for t_seckill_order_snapshot.goods_count
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order_snapshot.goods_price
     *
     * @return the value of t_seckill_order_snapshot.goods_price
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order_snapshot.goods_price
     *
     * @param goodsPrice the value for t_seckill_order_snapshot.goods_price
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order_snapshot.seckill_price
     *
     * @return the value of t_seckill_order_snapshot.seckill_price
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public BigDecimal getSeckillPrice() {
        return seckillPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order_snapshot.seckill_price
     *
     * @param seckillPrice the value for t_seckill_order_snapshot.seckill_price
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public void setSeckillPrice(BigDecimal seckillPrice) {
        this.seckillPrice = seckillPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order_snapshot.goods_name
     *
     * @return the value of t_seckill_order_snapshot.goods_name
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order_snapshot.goods_name
     *
     * @param goodsName the value for t_seckill_order_snapshot.goods_name
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order_snapshot.goods_title
     *
     * @return the value of t_seckill_order_snapshot.goods_title
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public String getGoodsTitle() {
        return goodsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order_snapshot.goods_title
     *
     * @param goodsTitle the value for t_seckill_order_snapshot.goods_title
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public void setGoodsTitle(String goodsTitle) {
        this.goodsTitle = goodsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order_snapshot.goods_img
     *
     * @return the value of t_seckill_order_snapshot.goods_img
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order_snapshot.goods_img
     *
     * @param goodsImg the value for t_seckill_order_snapshot.goods_img
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill_order_snapshot.goods_detail
     *
     * @return the value of t_seckill_order_snapshot.goods_detail
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public String getGoodsDetail() {
        return goodsDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill_order_snapshot.goods_detail
     *
     * @param goodsDetail the value for t_seckill_order_snapshot.goods_detail
     *
     * @mbg.generated Wed Feb 26 09:56:37 CST 2020
     */
    public void setGoodsDetail(String goodsDetail) {
        this.goodsDetail = goodsDetail;
    }
}