package com.wenyanwen123.buy.common.domain.learningdb;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_id
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.phone_num
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    private String phoneNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_name
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.salt
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.head_img
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    private String headImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.is_locked
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    private Boolean isLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.create_time
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.create_timestamp
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    private Integer createTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.last_login_timestamp
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    private Integer lastLoginTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.login_count
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    private Integer loginCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.phone_num
     *
     * @return the value of t_user.phone_num
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.phone_num
     *
     * @param phoneNum the value for t_user.phone_num
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_name
     *
     * @return the value of t_user.user_name
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_name
     *
     * @param userName the value for t_user.user_name
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.salt
     *
     * @return the value of t_user.salt
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.salt
     *
     * @param salt the value for t_user.salt
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.head_img
     *
     * @return the value of t_user.head_img
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.head_img
     *
     * @param headImg the value for t_user.head_img
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.is_locked
     *
     * @return the value of t_user.is_locked
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public Boolean getIsLocked() {
        return isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.is_locked
     *
     * @param isLocked the value for t_user.is_locked
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public void setIsLocked(Boolean isLocked) {
        this.isLocked = isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.create_time
     *
     * @return the value of t_user.create_time
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.create_time
     *
     * @param createTime the value for t_user.create_time
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.create_timestamp
     *
     * @return the value of t_user.create_timestamp
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public Integer getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.create_timestamp
     *
     * @param createTimestamp the value for t_user.create_timestamp
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public void setCreateTimestamp(Integer createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.last_login_timestamp
     *
     * @return the value of t_user.last_login_timestamp
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public Integer getLastLoginTimestamp() {
        return lastLoginTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.last_login_timestamp
     *
     * @param lastLoginTimestamp the value for t_user.last_login_timestamp
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public void setLastLoginTimestamp(Integer lastLoginTimestamp) {
        this.lastLoginTimestamp = lastLoginTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.login_count
     *
     * @return the value of t_user.login_count
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.login_count
     *
     * @param loginCount the value for t_user.login_count
     *
     * @mbg.generated Tue Feb 18 11:39:12 CST 2020
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }
}